{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sgrsoft.vision",
    "module": "vision",
    "version": "0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "vision-0.1.7.aar",
          "url": "vision-0.1.7.aar",
          "size": 165385,
          "sha512": "7a1618a46f5903d1a80171b4802240646af28e38fbfd48c4ebd472459e6aaef34dc565aff2f7677f4d2f1e90184e5386e55dc13af784af319ff00438365afbc5",
          "sha256": "0f25fe6c3a26084bdf167fea3c1baec12f6f28740305152f7a381ba4178f69f2",
          "sha1": "0f1b23b43c3ff8d66be180edf16a9a1c6b4dbded",
          "md5": "1f762072faf18624b912ceaab23a3504"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "vision-0.1.7.aar",
          "url": "vision-0.1.7.aar",
          "size": 165385,
          "sha512": "7a1618a46f5903d1a80171b4802240646af28e38fbfd48c4ebd472459e6aaef34dc565aff2f7677f4d2f1e90184e5386e55dc13af784af319ff00438365afbc5",
          "sha256": "0f25fe6c3a26084bdf167fea3c1baec12f6f28740305152f7a381ba4178f69f2",
          "sha1": "0f1b23b43c3ff8d66be180edf16a9a1c6b4dbded",
          "md5": "1f762072faf18624b912ceaab23a3504"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vision-0.1.7-sources.jar",
          "url": "vision-0.1.7-sources.jar",
          "size": 18213,
          "sha512": "6e8b9c3cb6cc42f440cb380b3c3089f776840ff0e80cd233055707c00c6189afe5834155e4d48211f08f573398a955a69dc1a169d33ae701833db52b2baf7c03",
          "sha256": "b7e575b4724dc30f860ec530da9daa910257e782ceaf04d5aa46029986e922ae",
          "sha1": "48375d1af26741a72175d8047834e5034e25ced6",
          "md5": "e6ba3cce4516c20149c49fbf34bcbbe0"
        }
      ]
    }
  ]
}
