{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sgrsoft.vision",
    "module": "vision",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "vision-0.1.3.aar",
          "url": "vision-0.1.3.aar",
          "size": 160522,
          "sha512": "718281db38e278e065bfc1aae554f8ca9b0aa2088297c85e44a1d686cc36222c1ed090ea3211a63472bfdf7e28b5bfbb89d8e68702e33f78b52643d1302c1d64",
          "sha256": "b3aeefa727a0077642224dd2c2515d663bd8b95c6b91b9b927362df01d05596c",
          "sha1": "7b0e35e1ab19a26f8176e6e8c9b3968f267704bf",
          "md5": "89f19f4662d393ca2a6855ec8f8d35aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "vision-0.1.3.aar",
          "url": "vision-0.1.3.aar",
          "size": 160522,
          "sha512": "718281db38e278e065bfc1aae554f8ca9b0aa2088297c85e44a1d686cc36222c1ed090ea3211a63472bfdf7e28b5bfbb89d8e68702e33f78b52643d1302c1d64",
          "sha256": "b3aeefa727a0077642224dd2c2515d663bd8b95c6b91b9b927362df01d05596c",
          "sha1": "7b0e35e1ab19a26f8176e6e8c9b3968f267704bf",
          "md5": "89f19f4662d393ca2a6855ec8f8d35aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vision-0.1.3-sources.jar",
          "url": "vision-0.1.3-sources.jar",
          "size": 17244,
          "sha512": "e954e02986aa25781360999c395aff724d167a45767521f3f7516ec1325a98833e856a2ff833166a1a1aad90959ab2cbf2854c5e33cde7b0ad2d3df16caabfd1",
          "sha256": "d1662690d7d5d57c9dfb1448f17ffe5d26063f5ea60f5c7302ba5cc4ca28b7db",
          "sha1": "b29faa4aa0fdfb6b093faba748cb36290fbfb312",
          "md5": "19ed51e97c05c44920b9b861c0fb3ddb"
        }
      ]
    }
  ]
}
