{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sgrsoft.vision",
    "module": "vision",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "vision-0.1.0.aar",
          "url": "vision-0.1.0.aar",
          "size": 157112,
          "sha512": "b33302934a66de9f1f38390bb12e5999eabc79efaf13f9cc400361bc07a2c86838a5dac8d9d259a532713113f8e0f12667f555aad868af22c08bd815eb85cff2",
          "sha256": "d19d3a7b8eb6e406ff2e041f78c7b03bb8920ef00ed6fcc313cd10be02198e1e",
          "sha1": "12ce5d0a5e09fdd3e288c4d1a51fad30afd6efb8",
          "md5": "6ac208d4829204d3711430d8dafe159a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "vision-0.1.0.aar",
          "url": "vision-0.1.0.aar",
          "size": 157112,
          "sha512": "b33302934a66de9f1f38390bb12e5999eabc79efaf13f9cc400361bc07a2c86838a5dac8d9d259a532713113f8e0f12667f555aad868af22c08bd815eb85cff2",
          "sha256": "d19d3a7b8eb6e406ff2e041f78c7b03bb8920ef00ed6fcc313cd10be02198e1e",
          "sha1": "12ce5d0a5e09fdd3e288c4d1a51fad30afd6efb8",
          "md5": "6ac208d4829204d3711430d8dafe159a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vision-0.1.0-sources.jar",
          "url": "vision-0.1.0-sources.jar",
          "size": 15763,
          "sha512": "f12f9772832278e6470528403f72d217de5f08a25037aa7ace133e426beedbaab2f5a466327aca87aa76e9719f264100a5f89a91b3978afae0310d518947bb1e",
          "sha256": "deed09574c4711d065722cbf5393c1a58664fadec80e7a6fadbe8bd94dc75363",
          "sha1": "7a61de9397fd868a68d26ee22e752cd3f0aa2a22",
          "md5": "acd80e33e2f7957ea16a323c9aca43d9"
        }
      ]
    }
  ]
}
