{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sgrsoft.vision",
    "module": "vision",
    "version": "0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "vision-0.1.8.aar",
          "url": "vision-0.1.8.aar",
          "size": 165456,
          "sha512": "3913be4879829068043a500a5840b00f13257cf37e0047f9b6bdceb42d03ff834336b8042ac35c989fa23d2dbb459f90103c1cefdd1c1c5a5282b95139243647",
          "sha256": "313230c8db6c2f73cb3e8e12bc7dd6e5096670df440a307c607d1763f94274f5",
          "sha1": "4c88fb695fe43bf808103c68ddf1b9ff34c82751",
          "md5": "4bf03a8f9561f3a166b7b60a9b298845"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "vision-0.1.8.aar",
          "url": "vision-0.1.8.aar",
          "size": 165456,
          "sha512": "3913be4879829068043a500a5840b00f13257cf37e0047f9b6bdceb42d03ff834336b8042ac35c989fa23d2dbb459f90103c1cefdd1c1c5a5282b95139243647",
          "sha256": "313230c8db6c2f73cb3e8e12bc7dd6e5096670df440a307c607d1763f94274f5",
          "sha1": "4c88fb695fe43bf808103c68ddf1b9ff34c82751",
          "md5": "4bf03a8f9561f3a166b7b60a9b298845"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vision-0.1.8-sources.jar",
          "url": "vision-0.1.8-sources.jar",
          "size": 18213,
          "sha512": "3c9400284f5660c805cebd581f1ced1b2d1db872da63ab375335fff074173a172a78bac206e1fdbb879e6044467bba09564240d9096817629f7ade8ac64f3994",
          "sha256": "9765becb45497feccbf67122408d6406926837457a18edd93fa3c4c221f4888e",
          "sha1": "06566189a577ea9a8286a7ea5d05105af0e9cfd4",
          "md5": "247ce49434de262d389ffd41e0fe5c85"
        }
      ]
    }
  ]
}
